<?php

namespace Database\Seeders;

use App\Models\Intervention;
use Illuminate\Database\Seeder;

class InterventionSeeder extends Seeder
{
    public function run(): void
    {
        $interventions = [
            // PHONEMIC AWARENESS (target_weakness = 1)
            [
                'name' => 'Sound Matching Game',
                'description' => 'Learner matches pictures of objects that start with the same sound.',
                'target_weakness' => 1,
                'activity_type' => 'game',
                'materials_needed' => 'Picture cards, letter cards',
                'instructions' => "1. Prepare picture cards of common objects.\n2. Lay out 5-6 cards on the table.\n3. Say a letter sound (e.g., /b/).\n4. Ask the learner to find all pictures starting with that sound.\n5. Repeat with different sounds.\n6. Increase difficulty by using ending sounds.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 3,
                'estimated_duration' => 15, 'effectiveness_score' => 7.5,
            ],
            [
                'name' => 'Rhyme Time',
                'description' => 'Learner identifies and creates rhyming words through songs and word play.',
                'target_weakness' => 1,
                'activity_type' => 'game',
                'materials_needed' => 'Word cards, nursery rhyme charts',
                'instructions' => "1. Read a nursery rhyme or simple poem aloud.\n2. Emphasize the rhyming words.\n3. Ask: \"What words sound the same at the end?\"\n4. Give a word and ask the learner to think of rhyming words.\n5. Create silly rhyming sentences together.\n6. Practice 5-10 rhyming pairs each session.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 3,
                'estimated_duration' => 15, 'effectiveness_score' => 7.0,
            ],
            [
                'name' => 'Syllable Clapping',
                'description' => 'Learner claps syllables in words to develop phonological awareness.',
                'target_weakness' => 1,
                'activity_type' => 'drill',
                'materials_needed' => 'Word list with 1-4 syllable words',
                'instructions' => "1. Say a word aloud (e.g., \"butterfly\").\n2. Clap for each syllable: but-ter-fly (3 claps).\n3. Have the learner repeat and clap.\n4. Start with 1-syllable words, then 2, 3, 4.\n5. Use learner's name and familiar words.\n6. Try segmenting: \"How many parts in ba-na-na?\"",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 4,
                'estimated_duration' => 10, 'effectiveness_score' => 8.0,
            ],
            [
                'name' => 'Sound Blending Practice',
                'description' => 'Learner blends individual sounds to form words.',
                'target_weakness' => 1,
                'activity_type' => 'drill',
                'materials_needed' => 'Letter cards or whiteboard',
                'instructions' => "1. Say individual sounds slowly: /c/ - /a/ - /t/.\n2. Ask the learner: \"What word do these sounds make?\"\n3. Start with 2-sound words (e.g., at, in).\n4. Progress to 3-sound words (e.g., cat, dog).\n5. Use letter cards to make it visual.\n6. Celebrate each correct blend.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 3,
                'estimated_duration' => 15, 'effectiveness_score' => 8.5,
            ],
            [
                'name' => 'Phoneme Isolation Game',
                'description' => 'Learner identifies beginning, middle, and ending sounds in words.',
                'target_weakness' => 1,
                'activity_type' => 'game',
                'materials_needed' => 'Picture cards, sound boxes template',
                'instructions' => "1. Show a picture card (e.g., sun).\n2. Ask: \"What is the first sound in sun?\" (/s/)\n3. Ask: \"What is the last sound in sun?\" (/n/)\n4. Use Elkonin boxes: draw 3 boxes, place tokens for each sound.\n5. Practice with 10-15 words per session.\n6. Start with beginning sounds, then end, then middle.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 3,
                'estimated_duration' => 15, 'effectiveness_score' => 7.5,
            ],

            // DECODING ACCURACY (target_weakness = 2)
            [
                'name' => 'Sight Word Flash Cards',
                'description' => 'Learner practices reading high-frequency sight words instantly.',
                'target_weakness' => 2,
                'activity_type' => 'drill',
                'materials_needed' => 'Sight word flash cards (Dolch or Fry list)',
                'instructions' => "1. Select 5-10 sight words appropriate for learner's level.\n2. Show each card for 3 seconds.\n3. If learner reads correctly, place in \"Known\" pile.\n4. If incorrect, say the word and have learner repeat 3 times.\n5. Review \"Unknown\" words again.\n6. Add 2-3 new words when learner masters current set.\n7. Track progress on a sight word chart.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 4,
                'estimated_duration' => 10, 'effectiveness_score' => 8.0,
            ],
            [
                'name' => 'Word Family Activities',
                'description' => 'Learner builds words using common word family patterns (-at, -an, -ig, etc.).',
                'target_weakness' => 2,
                'activity_type' => 'drill',
                'materials_needed' => 'Word family cards, whiteboard or paper',
                'instructions' => "1. Write the word family ending (e.g., -at).\n2. Add different beginning letters: b-at, c-at, h-at, m-at.\n3. Have learner read each word.\n4. Let learner create their own words.\n5. Use each word in a simple sentence.\n6. Practice 2-3 word families per session.\n7. Progress from CVC to CCVC patterns.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 4,
                'estimated_duration' => 15, 'effectiveness_score' => 7.5,
            ],
            [
                'name' => 'Syllable Division Practice',
                'description' => 'Learner learns to break multi-syllable words into readable parts.',
                'target_weakness' => 2,
                'activity_type' => 'drill',
                'materials_needed' => 'Multi-syllable word list, paper and pencil',
                'instructions' => "1. Show a long word (e.g., \"butterfly\").\n2. Demonstrate how to divide: but-ter-fly.\n3. Teach simple rules: divide between consonants (nap-kin).\n4. Have learner draw lines between syllables.\n5. Read each syllable, then blend together.\n6. Practice with words from their reading material.\n7. Use words from Filipino and English.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 2, 'grade_level_max' => 6,
                'estimated_duration' => 15, 'effectiveness_score' => 7.0,
            ],
            [
                'name' => 'Phonics Pattern Drills',
                'description' => 'Learner practices common phonics patterns (consonant blends, digraphs, vowel teams).',
                'target_weakness' => 2,
                'activity_type' => 'drill',
                'materials_needed' => 'Phonics pattern cards, decodable readers',
                'instructions' => "1. Introduce one pattern per session (e.g., \"th\" digraph).\n2. Show examples: the, this, that, them, they.\n3. Have learner read each word.\n4. Find the pattern in a short passage.\n5. Write 3 sentences using words with the pattern.\n6. Review previous patterns before introducing new ones.\n7. Keep a \"Patterns I Know\" chart.",
                'for_teacher' => true, 'for_parent' => false,
                'grade_level_min' => 1, 'grade_level_max' => 5,
                'estimated_duration' => 20, 'effectiveness_score' => 7.5,
            ],
            [
                'name' => 'Decodable Story Reading',
                'description' => 'Learner reads stories composed mostly of words they can decode with known patterns.',
                'target_weakness' => 2,
                'activity_type' => 'reading',
                'materials_needed' => 'Decodable readers or printed stories',
                'instructions' => "1. Select a decodable story matching learned phonics patterns.\n2. Preview vocabulary: discuss 3-4 new words.\n3. Learner reads aloud. Pause at difficult words.\n4. Prompt: \"What sounds do you see? Can you blend them?\"\n5. Re-read the story for fluency.\n6. Ask 2-3 comprehension questions.\n7. Celebrate progress and effort.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 4,
                'estimated_duration' => 20, 'effectiveness_score' => 8.0,
            ],

            // ORAL READING FLUENCY (target_weakness = 3)
            [
                'name' => 'Repeated Reading Practice',
                'description' => 'Learner reads the same passage multiple times to improve speed and accuracy.',
                'target_weakness' => 3,
                'activity_type' => 'reading',
                'materials_needed' => 'Grade-level passage (50-150 words), timer, progress chart',
                'instructions' => "1. Select a passage at learner's instructional level.\n2. Teacher reads the passage aloud first (model fluent reading).\n3. Learner reads the passage aloud. Time and count errors.\n4. Record WPM and errors on chart.\n5. Learner practices reading the same passage 3-4 more times.\n6. Time each reading and record improvement.\n7. Celebrate when WPM increases or errors decrease.\n8. Move to new passage when learner reaches target WPM.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 8,
                'estimated_duration' => 15, 'effectiveness_score' => 9.0,
            ],
            [
                'name' => 'Echo Reading',
                'description' => 'Teacher reads a sentence and learner immediately repeats it with the same expression and pace.',
                'target_weakness' => 3,
                'activity_type' => 'reading',
                'materials_needed' => 'Reading passage, audio recorder (optional)',
                'instructions' => "1. Select a passage at appropriate level.\n2. Read one sentence aloud with good expression.\n3. Learner \"echoes\" - reads the same sentence.\n4. Focus on matching your pace and expression.\n5. Move to the next sentence.\n6. After echo reading, learner reads the whole passage alone.\n7. Record and compare the echo reading vs. solo reading.\n8. Use passages from English and Filipino.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 6,
                'estimated_duration' => 15, 'effectiveness_score' => 8.5,
            ],
            [
                'name' => 'Phrase-Cued Text Reading',
                'description' => 'Passages are marked with phrase boundaries to help learner read in meaningful chunks.',
                'target_weakness' => 3,
                'activity_type' => 'reading',
                'materials_needed' => 'Phrase-marked passages (use slashes to mark phrases)',
                'instructions' => "1. Prepare a passage with phrase markings:\n   \"The boy / went to the store / to buy bread.\"\n2. Explain that good readers read in phrases, not word-by-word.\n3. Model reading the phrases smoothly.\n4. Learner practices reading by phrases.\n5. Gradually reduce phrase markings.\n6. Compare word-by-word reading vs. phrase reading.\n7. Practice with 2-3 passages per session.",
                'for_teacher' => true, 'for_parent' => false,
                'grade_level_min' => 1, 'grade_level_max' => 6,
                'estimated_duration' => 15, 'effectiveness_score' => 7.5,
            ],
            [
                'name' => 'Reader\'s Theater',
                'description' => 'Learners perform a short script with assigned roles, building fluency through practice.',
                'target_weakness' => 3,
                'activity_type' => 'reading',
                'materials_needed' => 'Reader\'s theater scripts (2-4 characters)',
                'instructions' => "1. Choose a simple script appropriate for learner's level.\n2. Assign character roles.\n3. Read through the script together once.\n4. Each person practices their lines.\n5. Perform the script with expression.\n6. Focus on: volume, pace, emotion, pausing at punctuation.\n7. Can record and play back for self-evaluation.\n8. Perform for family members or classmates.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 2, 'grade_level_max' => 8,
                'estimated_duration' => 30, 'effectiveness_score' => 8.0,
            ],
            [
                'name' => 'Paired Reading with Audio Model',
                'description' => 'Learner listens to audio of fluent reading while following along, then reads alone.',
                'target_weakness' => 3,
                'activity_type' => 'audio',
                'materials_needed' => 'Audio recording of passage, printed passage',
                'instructions' => "1. Provide the learner with a printed passage.\n2. Play audio of the passage read fluently.\n3. Learner follows along, pointing to each word.\n4. Play again - learner reads along with the audio (choral).\n5. Learner reads alone. Time and note improvements.\n6. Repeat daily with the same passage for one week.\n7. Move to new passage the following week.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 6,
                'estimated_duration' => 15, 'effectiveness_score' => 8.0,
            ],

            // READING COMPREHENSION (target_weakness = 4)
            [
                'name' => 'Story Mapping',
                'description' => 'Learner completes a graphic organizer identifying story elements after reading.',
                'target_weakness' => 4,
                'activity_type' => 'writing',
                'materials_needed' => 'Story map template, reading passage, pencil',
                'instructions' => "1. Read a short story together.\n2. Provide a story map template with sections:\n   - Characters (Who?)\n   - Setting (Where? When?)\n   - Problem (What happened?)\n   - Events (What did they do?)\n   - Solution (How did it end?)\n3. Guide learner to fill in each section.\n4. Discuss: \"Why do you think that happened?\"\n5. Let learner retell the story using their map.\n6. Practice with different stories each session.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 6,
                'estimated_duration' => 20, 'effectiveness_score' => 8.0,
            ],
            [
                'name' => 'Question-Answer Relationships (QAR)',
                'description' => 'Learner identifies where answers come from: in the text, in their head, or both.',
                'target_weakness' => 4,
                'activity_type' => 'drill',
                'materials_needed' => 'Reading passage, QAR chart, question cards',
                'instructions' => "1. Teach four question types:\n   - Right There: answer is in one sentence.\n   - Think and Search: answer is in multiple parts of text.\n   - Author and Me: combine text info with what you know.\n   - On My Own: use your own experience.\n2. Read a passage together.\n3. Ask questions of each type.\n4. Learner identifies the question type first, then answers.\n5. Practice categorizing questions before answering.\n6. Create questions together.",
                'for_teacher' => true, 'for_parent' => false,
                'grade_level_min' => 3, 'grade_level_max' => 8,
                'estimated_duration' => 20, 'effectiveness_score' => 7.5,
            ],
            [
                'name' => 'Before-During-After Reading Strategy',
                'description' => 'Structured approach to reading that builds comprehension at each stage.',
                'target_weakness' => 4,
                'activity_type' => 'reading',
                'materials_needed' => 'Reading passage, BDA chart',
                'instructions' => "1. BEFORE reading:\n   - Look at title and pictures. Predict: \"What might this be about?\"\n   - Activate prior knowledge: \"What do you already know about this?\"\n2. DURING reading:\n   - Pause after each paragraph.\n   - Ask: \"What just happened? What do you think will happen next?\"\n   - Identify unfamiliar words and discuss meanings.\n3. AFTER reading:\n   - Summarize: \"Tell me what the story was about in 3 sentences.\"\n   - Connect: \"Has something like this happened to you?\"\n   - Evaluate: \"Did you like the story? Why or why not?\"",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 8,
                'estimated_duration' => 25, 'effectiveness_score' => 8.5,
            ],
            [
                'name' => 'Visualization Exercises',
                'description' => 'Learner creates mental images while listening to or reading text.',
                'target_weakness' => 4,
                'activity_type' => 'visual',
                'materials_needed' => 'Reading passage, drawing materials',
                'instructions' => "1. Read a descriptive paragraph aloud slowly.\n2. Ask learner to close eyes and \"see\" the story in their mind.\n3. Ask: \"What did you see? What colors? What sounds?\"\n4. Learner draws what they imagined.\n5. Read another section. Learner adds to their drawing.\n6. Compare drawing to the text details.\n7. Discuss: \"Did you imagine the same thing as the author described?\"\n8. Practice with descriptive passages from Filipino and English.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 1, 'grade_level_max' => 6,
                'estimated_duration' => 20, 'effectiveness_score' => 7.0,
            ],
            [
                'name' => 'Retelling and Summarizing',
                'description' => 'Learner practices retelling stories or information in their own words.',
                'target_weakness' => 4,
                'activity_type' => 'drill',
                'materials_needed' => 'Reading passage, retelling rubric',
                'instructions' => "1. Read a short passage together.\n2. Close the book or turn over the paper.\n3. Ask: \"Can you tell me what you just read?\"\n4. Use prompts: \"Who? What happened first? Then? Finally?\"\n5. For informational text: \"What are the 3 main things you learned?\"\n6. Compare retelling to original - what was included? missed?\n7. Practice reducing to just 2-3 sentences (summarizing).\n8. Rate retelling: complete, partial, or minimal.",
                'for_teacher' => true, 'for_parent' => true,
                'grade_level_min' => 2, 'grade_level_max' => 8,
                'estimated_duration' => 15, 'effectiveness_score' => 7.5,
            ],
        ];

        foreach ($interventions as $intervention) {
            Intervention::create($intervention);
        }
    }
}
