<?php

namespace Database\Seeders;

use App\Models\ReadingMaterial;
use Illuminate\Database\Seeder;

class ReadingMaterialSeeder extends Seeder
{
    public function run(): void
    {
        $materials = [
            // Grade 1 English
            ['title' => 'My Pet Dog', 'content' => 'I have a dog. His name is Max. Max is brown. He has a long tail. Max likes to run. He runs in the park. I play with Max. We play catch. Max catches the ball. He brings it back to me. I love my dog Max.', 'language' => 'en', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 52, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'The Red Ball', 'content' => 'I have a red ball. It is round. I kick the ball. It goes far. My friend runs to get it. She throws the ball to me. I catch it with my hands. We play all day. Playing ball is fun. I like my red ball.', 'language' => 'en', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 50, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Going to School', 'content' => 'I wake up early. I eat my breakfast. I brush my teeth. I put on my uniform. My bag is ready. I walk to school with my mother. I see my friends. We go to our classroom. Our teacher is kind. I love going to school.', 'language' => 'en', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 48, 'category' => 'narrative', 'source' => 'Original'],

            // Grade 2 English
            ['title' => 'The Helpful Boy', 'content' => 'Mario is a helpful boy. He helps his mother at home. He sweeps the floor every morning. He waters the plants in the garden. At school, Mario helps his teacher carry books. His classmates like him because he is always ready to help. Mario feels happy when he helps others. His mother is proud of him.', 'language' => 'en', 'grade_level' => 2, 'difficulty' => 'easy', 'word_count' => 56, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'A Rainy Day', 'content' => 'Today it is raining. The sky is dark and gray. Drops of water fall from the clouds. I can hear the rain on the roof. Children run inside the house. They do not want to get wet. Mother makes hot chocolate for us. We sit by the window and watch the rain. The flowers in the garden are happy. They need the rain to grow. After the rain, I see a beautiful rainbow in the sky.', 'language' => 'en', 'grade_level' => 2, 'difficulty' => 'medium', 'word_count' => 78, 'category' => 'narrative', 'source' => 'Original'],

            // Grade 3 English
            ['title' => 'The Farmers Market', 'content' => 'Every Saturday, my family goes to the farmers market. It is a big open area near the town hall. Many farmers bring fresh fruits and vegetables to sell. I can see green mangoes, ripe bananas, and red tomatoes. My mother buys rice, fish, and vegetables for the week. I help her carry the bags. Sometimes my father buys me a treat, like fresh coconut juice. The farmers market is always busy and noisy, but I enjoy going there because I like to see all the colorful food.', 'language' => 'en', 'grade_level' => 3, 'difficulty' => 'medium', 'word_count' => 90, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'How Plants Grow', 'content' => 'Plants need several things to grow. First, they need sunlight. The sun gives plants energy to make their own food. Second, they need water. Water helps carry nutrients from the soil to the leaves. Third, plants need soil. The soil has important minerals that help plants stay healthy. Finally, plants need air. They take in carbon dioxide from the air and release oxygen. When plants have all these things, they grow big and strong. Without even one of these, a plant may become weak or die.', 'language' => 'en', 'grade_level' => 3, 'difficulty' => 'medium', 'word_count' => 92, 'category' => 'expository', 'source' => 'Original'],

            // Grade 4 English
            ['title' => 'The Legend of the Firefly', 'content' => 'Long ago, in a small village in the Philippines, there lived a young girl named Alitaptap. She was known for her kind heart and gentle spirit. One night, a terrible storm came. The whole village was covered in darkness. People were afraid because they could not see anything. Alitaptap wanted to help her neighbors. She prayed to the heavens for light. Suddenly, a small glow appeared on her fingertips. She ran through the village, touching the trees and flowers. Each one began to glow. The village was filled with tiny lights. When morning came, the lights did not disappear. They became the first fireflies. To this day, the people of the village believe that fireflies carry the spirit of Alitaptap, lighting the way for those who are lost in the dark.', 'language' => 'en', 'grade_level' => 4, 'difficulty' => 'medium', 'word_count' => 148, 'category' => 'narrative', 'source' => 'Philippine Folklore'],

            // Grade 5 English
            ['title' => 'The Water Cycle', 'content' => 'The water cycle is one of the most important processes on Earth. It describes how water moves continuously between the surface of the Earth and the atmosphere. The cycle begins with evaporation. When the sun heats water in oceans, rivers, and lakes, the water turns into water vapor and rises into the air. As the vapor rises higher, it cools down and changes back into tiny water droplets through a process called condensation. These droplets come together to form clouds. When the clouds become heavy with water, the droplets fall back to Earth as precipitation, which can be rain, snow, sleet, or hail. The water then flows into rivers, lakes, and oceans, or seeps into the ground. This cycle repeats over and over again, providing fresh water for all living things on our planet.', 'language' => 'en', 'grade_level' => 5, 'difficulty' => 'hard', 'word_count' => 152, 'category' => 'expository', 'source' => 'Science Textbook Adaptation'],

            // Grade 6 English
            ['title' => 'The Importance of Reading', 'content' => 'Reading is one of the most valuable skills a person can develop. It opens doors to knowledge, imagination, and understanding of the world around us. When we read, we encounter new ideas, different cultures, and perspectives that we might never experience in our daily lives. Studies have shown that regular reading improves vocabulary, enhances critical thinking skills, and strengthens memory. For students, reading is essential for academic success across all subjects, not just language arts. A student who reads well can understand science textbooks, solve word problems in mathematics, and analyze historical documents. Beyond academics, reading also develops empathy. When readers follow characters through challenging situations, they learn to understand and feel what others experience. In todays digital age, where information is everywhere, the ability to read critically and comprehend complex texts is more important than ever. Developing a love for reading early in life creates a foundation for lifelong learning and personal growth.', 'language' => 'en', 'grade_level' => 6, 'difficulty' => 'hard', 'word_count' => 166, 'category' => 'expository', 'source' => 'Original'],

            // Grade 7 English
            ['title' => 'Digital Citizenship', 'content' => 'In the twenty-first century, being a responsible citizen extends beyond our physical communities into the digital world. Digital citizenship refers to the norms of appropriate and responsible behavior when using technology and the internet. As young people spend increasing amounts of time online, understanding digital citizenship has become essential. There are several key aspects of being a good digital citizen. First, digital literacy involves the ability to find, evaluate, and communicate information effectively. Not everything found online is accurate or reliable, and students must learn to distinguish credible sources from misinformation. Second, online safety means protecting personal information and being aware of potential dangers such as cyberbullying, phishing, and identity theft. Third, digital etiquette involves treating others with respect in online interactions, just as we would in face-to-face conversations. Finally, understanding digital rights and responsibilities means knowing that our online actions have real consequences and that we are accountable for our behavior in digital spaces.', 'language' => 'en', 'grade_level' => 7, 'difficulty' => 'hard', 'word_count' => 168, 'category' => 'expository', 'source' => 'Original'],

            // Filipino
            ['title' => 'Ang Pusa Ko', 'content' => 'Ako ay may pusa. Ang pangalan niya ay Muning. Si Muning ay puti. Mahaba ang buntot niya. Mahilig siyang matulog. Natutulog siya sa ilalim ng mesa. Pinapakain ko siya araw-araw. Binibigyan ko siya ng gatas. Mahal ko ang pusa ko.', 'language' => 'fil', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 42, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Si Nanay', 'content' => 'Si Nanay ay mabait. Maaga siyang gumigising. Nagluluto siya ng almusal. Inaayos niya ang bahay. Tinutulungan niya kami sa takdang-aralin. Sa gabi, nagkukuwento siya bago kami matulog. Masarap ang kwento ni Nanay. Mahal na mahal ko si Nanay.', 'language' => 'fil', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 40, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Ang Aming Paaralan', 'content' => 'Ang paaralan namin ay malaki. Maraming silid-aralan. May malawak na patyo kung saan kami naglalaro. May hardin din sa harap ng paaralan. Ang mga guro namin ay mababait at matulungin. Tinuturuan nila kami na magbasa at magsulat. Natututo rin kami ng matematika at agham. Masaya ako sa aming paaralan dahil marami akong natutunan. Ang aking mga kaibigan ay mababait din. Lagi kaming nagtutulungan sa klase.', 'language' => 'fil', 'grade_level' => 2, 'difficulty' => 'medium', 'word_count' => 70, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Ang Pagtulong sa Kapwa', 'content' => 'Ang pagtulong sa kapwa ay isang magandang ugali na dapat nating isabuhay. Hindi kailangan ng malaking bagay para makatulong. Kahit sa simpleng paraan, makakatulong na tayo. Maaari tayong tumulong sa mga matatanda sa pagtawid ng kalsada. Maaari rin tayong magbigay ng pagkain sa mga nangangailangan. Sa paaralan, matutulungan natin ang ating mga kaklase sa kanilang mga aralin. Sa bahay, matutulungan natin si Nanay at Tatay sa mga gawaing bahay. Kapag tayo ay tumutulong, nagiging masaya tayo at ang mga taong ating tinutulungan. Tandaan natin na ang bawat maliit na tulong ay may malaking halaga sa iba.', 'language' => 'fil', 'grade_level' => 3, 'difficulty' => 'medium', 'word_count' => 104, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Ang Kahalagahan ng Edukasyon', 'content' => 'Ang edukasyon ay isa sa pinakamahalagang bagay na maaari nating makamtan sa buhay. Sa pamamagitan ng edukasyon, nagkakaroon tayo ng kaalaman at kasanayan na makakatulong sa atin sa hinaharap. Ang isang taong may mataas na pinag-aralan ay may mas malawak na pagkakataon sa buhay. Maaari siyang makahanap ng magandang trabaho at makapagbigay ng maayos na pamumuhay sa kanyang pamilya. Ngunit ang edukasyon ay hindi lamang tungkol sa pag-aaral sa paaralan. Natututo rin tayo sa mga karanasan sa araw-araw na buhay. Ang mga magulang, guro, at kaibigan ay mga tagapagturo rin natin. Mahalaga na pahalagahan natin ang bawat pagkakataong matuto, dahil ang kaalaman ay isang yaman na hindi mananakaw ninuman.', 'language' => 'fil', 'grade_level' => 5, 'difficulty' => 'hard', 'word_count' => 130, 'category' => 'expository', 'source' => 'Original'],

            // Filipino
            ['title' => 'Ang Akon Ido', 'content' => 'May ido ako. Ang ngalan niya si Bantay. Si Bantay itom kag dako. Mahaba ang iya ikog. Gusto niya magdalagan sa plasa. Nagakaon siya sang kan-on kag isda. Ginapakain ko siya adlaw-adlaw. Palangga ko gid ang akon ido nga si Bantay.', 'language' => 'hil', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 42, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Ang Amon Balay', 'content' => 'Ang amon balay ara sa Sagay. Gamay lang ini pero matahom. May hardin kami sa atubangan. May mga bulak kag tanom sa hardin. Si Nanay nagaasiwa sang balay. Si Tatay nagaobra sa uma. Kami sang akon mga utod nagabulig sa mga hilikuton. Malipayon kami sa amon balay.', 'language' => 'hil', 'grade_level' => 1, 'difficulty' => 'easy', 'word_count' => 48, 'category' => 'narrative', 'source' => 'Original'],
            ['title' => 'Ang Pista sa Sagay', 'content' => 'Kada tuig, may pista ang Sagay City. Ginakilala ini bilang Sinigayan Festival. Madamo nga tawo ang nagakadto sa pista. May mga parada kag sayaw sa kalsada. May mga kaon-kaon nga matamis kag maaslom. Ang mga bata nagalingaw sa mga dulaan. Ang mga tigulang nagaistorya kag nagakadlaw. Ang pista isa ka tion nga nagatipon ang tanan nga mga Sagaynon. Malipayon gid ini nga okasyon para sa amon siyudad.', 'language' => 'hil', 'grade_level' => 3, 'difficulty' => 'medium', 'word_count' => 72, 'category' => 'narrative', 'source' => 'Original'],
        ];

        foreach ($materials as $material) {
            ReadingMaterial::create($material);
        }
    }
}
