<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report - {{ $learner->full_name }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        @media print {
            .no-print { display: none !important; }
            body { font-size: 12px; }
        }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
    </style>
</head>
<body class="p-4">
    <div class="no-print text-end mb-3">
        <button onclick="window.print()" class="btn btn-primary btn-sm"><i class="bi bi-printer"></i> Print</button>
        <a href="{{ route('reports.learner', $learner) }}" class="btn btn-outline-secondary btn-sm">Back</a>
    </div>

    {{-- Header --}}
    <div class="text-center mb-4">
        <h4 class="fw-bold">BIGKAS-AI</h4>
        <p class="text-muted mb-0">AI-Assisted Reading Assessment Report</p>
        <hr>
    </div>

    {{-- Learner Info --}}
    <div class="row mb-4">
        <div class="col-6">
            <table class="table table-sm table-borderless">
                <tr><th width="40%">Name:</th><td>{{ $learner->full_name }}</td></tr>
                <tr><th>LRN:</th><td>{{ $learner->lrn ?? 'N/A' }}</td></tr>
                <tr><th>Grade Level:</th><td>Grade {{ $learner->grade_level }}</td></tr>
                <tr><th>Gender:</th><td>{{ ucfirst($learner->gender ?? 'N/A') }}</td></tr>
            </table>
        </div>
        <div class="col-6">
            <table class="table table-sm table-borderless">
                <tr><th width="40%">School:</th><td>{{ $learner->school?->name ?? 'N/A' }}</td></tr>
                <tr><th>Class:</th><td>{{ $learner->schoolClass?->name ?? 'N/A' }}</td></tr>
                <tr><th>Mother Tongue:</th><td>{{ ucfirst($learner->mother_tongue ?? 'N/A') }}</td></tr>
                <tr><th>Reading Level:</th><td><strong>{{ ucfirst($learner->reading_level ?? 'Not Assessed') }}</strong></td></tr>
            </table>
        </div>
    </div>

    {{-- Assessment History --}}
    <h6 class="fw-bold">Assessment History</h6>
    <table class="table table-bordered table-sm">
        <thead class="table-light">
            <tr><th>Date</th><th>Material</th><th>Accuracy</th><th>WPM</th><th>Level</th><th>Primary Weakness</th></tr>
        </thead>
        <tbody>
            @php $weaknessLabels = config('bigkas.weakness_categories', []); @endphp
            @forelse($assessments ?? [] as $a)
                @php $r = $a->results->first(); @endphp
                <tr>
                    <td>{{ $a->created_at?->format('M d, Y') }}</td>
                    <td>{{ $a->material?->title ?? 'N/A' }}</td>
                    <td>{{ $r?->accuracy_rate ?? '-' }}%</td>
                    <td>{{ $r?->words_per_minute ?? '-' }}</td>
                    <td>{{ ucfirst($r?->reading_level ?? '-') }}</td>
                    <td>{{ $weaknessLabels[$r?->primary_weakness]['name'] ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="6" class="text-center">No assessments</td></tr>
            @endforelse
        </tbody>
    </table>

    {{-- Footer --}}
    <div class="mt-5 text-center small text-muted">
        <p>Generated by BIGKAS-AI on {{ now()->format('F d, Y g:i A') }}</p>
        <p>Sagay City Division, Negros Occidental</p>
    </div>
</body>
</html>
